from .login import *
from .signup import *
from .main import *
from .password_reset import *
from .config import *
from .exercise import *
from .about import *
from .feedback import *
from .routine import *