# Generated by Django 4.2.5 on 2023-09-18 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_remove_user_name_remove_user_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
