# Generated by Django 4.2.5 on 2023-09-24 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='username',
        ),
    ]
