# Generated by Django 4.2.5 on 2023-10-08 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='actie',
            field=models.BooleanField(default=False),
        ),
    ]
