# Generated by Django 4.2.5 on 2023-10-24 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_alter_user_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_active',
            new_name='is_admin',
        ),
    ]
