# Generated by Django 4.2.5 on 2023-10-24 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0018_rename_is_active_user_is_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_admin',
            new_name='is_staff',
        ),
    ]
