# Generated by Django 4.2.5 on 2023-11-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0024_exercise_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='logo',
            field=models.CharField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='exercise',
            name='url',
            field=models.CharField(blank=True, unique=True),
        ),
    ]
