# Generated by Django 4.2.5 on 2023-11-06 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0025_exercise_logo_exercise_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='group',
            field=models.CharField(blank=True, choices=[('Pierna', 'LEGS'), ('Brazo', 'ARMS'), ('Abdomen', 'ABDOMINALS'), ('Pecho', 'CHEST'), ('Espalda', 'BACK'), ('Hombros', 'SHOULDERS')]),
        ),
    ]
