# Generated by Django 4.2.5 on 2023-11-28 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0029_routine'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='name',
            field=models.CharField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
