# Generated by Django 4.2.5 on 2023-11-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0030_routine_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='description',
            field=models.CharField(default=0),
            preserve_default=False,
        ),
    ]
