# Generated by Django 4.2.5 on 2023-11-28 02:42

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0031_routine_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='description',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(), size=None),
        ),
    ]
