# Generated by Django 4.2.5 on 2023-11-28 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0032_alter_routine_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='routine',
            name='logo',
            field=models.CharField(default=0, unique=True),
            preserve_default=False,
        ),
    ]
