# Generated by Django 4.2.5 on 2023-11-28 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0034_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='action',
            field=models.CharField(),
        ),
    ]
